######################################################################
# Automatically generated by qmake (2.01a) Wed Apr 24 08:49:48 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += dragon.h mainwindow.h obstacle.h
SOURCES += dragon.cpp game.cpp mainwindow.cpp obstacle.cpp
