######################################################################
# Automatically generated by qmake (2.01a) Tue Apr 23 06:54:44 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
SOURCES += game.cpp mainwindow.cpp
