######################################################################
# Automatically generated by qmake (2.01a) Sat Jan 24 02:18:57 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += dragon.h mainwindow.h obstacle.h
SOURCES += dragon.cpp game.cpp mainwindow.cpp obstacle.cpp
